package GiaoDienChinh;

import FrontEnd.BanHang.FrontEndBanHang;
import FrontEnd.HoaDon.FrontEndHoaDon;
import FrontEnd.LoaiSanPham.FrontEndLoaiSanPham;
import FrontEnd.SanPham.FrontEndSanPham;
import FrontEnd.NhaCungCap.FrontEndNhaCungCap;
import FrontEnd.NhanVien.FrontEndNhanVien;
import FrontEnd.NhapHang.FrontEndNhapHang;
import FrontEnd.PhieuNhap.FrontEndPhieuNhap;
import FrontEnd.KhachHang.FrontEndKhachHang;
import Login.Login;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLayout(null);
        setLocationRelativeTo(null);
    }

    private void tieuDe(JButton btn) {
        lbTenBtn.setText(btn.getText().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrMenu = new javax.swing.ButtonGroup();
        pnW = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        pnBanHang = new javax.swing.JPanel();
        btnBanHang = new javax.swing.JButton();
        pnNhapHang = new javax.swing.JPanel();
        btnNhapHang = new javax.swing.JButton();
        pnSanPham = new javax.swing.JPanel();
        btnSanPham = new javax.swing.JButton();
        pnLoaiSanPham = new javax.swing.JPanel();
        btnLoaiSanPham = new javax.swing.JButton();
        pnHoaDon = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        pnPhieuNhap = new javax.swing.JPanel();
        btnPhieuNhap = new javax.swing.JButton();
        pnNhanVien = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        pnKhachHang = new javax.swing.JPanel();
        btnKhachHang = new javax.swing.JButton();
        pnNhaCungCap = new javax.swing.JPanel();
        btnNhaCungCap = new javax.swing.JButton();
        pnN = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        lbTenBtn = new javax.swing.JLabel();
        pnContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        pnW.setBackground(new java.awt.Color(0, 77, 97));
        pnW.setForeground(new java.awt.Color(255, 255, 255));
        pnW.setAlignmentX(0.0F);
        pnW.setAlignmentY(0.0F);
        pnW.setMinimumSize(new java.awt.Dimension(0, 0));
        pnW.setPreferredSize(new java.awt.Dimension(180, 600));
        pnW.setLayout(new java.awt.GridLayout(10, 1, 150, 0));

        btnLogout.setBackground(null
        );
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnGrMenu.add(btnLogout);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnW.add(btnLogout);

        pnBanHang.setBackground(null
        );
        pnBanHang.setForeground(null
        );
        pnBanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnBanHang.setLayout(null);

        btnBanHang.setBackground(new java.awt.Color(255, 255, 255));
        btnBanHang.setFont(new java.awt.Font("Myriad Pro", 1, 13)); // NOI18N
        btnBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/banhang.png"))); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.setBorder(null);
        btnBanHang.setBorderPainted(false);
        btnGrMenu.add(btnBanHang);
        btnBanHang.setContentAreaFilled(false);
        btnBanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBanHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        pnBanHang.add(btnBanHang);
        btnBanHang.setBounds(40, 0, 140, 60);

        pnW.add(pnBanHang);

        pnNhapHang.setBackground(null
        );
        pnNhapHang.setForeground(null
        );
        pnNhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnNhapHang.setLayout(null);

        btnNhapHang.setBackground(new java.awt.Color(255, 255, 255));
        btnNhapHang.setFont(new java.awt.Font("Myriad Pro", 1, 13)); // NOI18N
        btnNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/nhaphang.png"))); // NOI18N
        btnNhapHang.setText("NHẬP HÀNG");
        btnNhapHang.setBorder(null);
        btnNhapHang.setBorderPainted(false);
        btnGrMenu.add(btnNhapHang);
        btnNhapHang.setContentAreaFilled(false);
        btnNhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhapHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });
        pnNhapHang.add(btnNhapHang);
        btnNhapHang.setBounds(40, 0, 140, 60);

        pnW.add(pnNhapHang);

        pnSanPham.setBackground(null
        );
        pnSanPham.setForeground(null
        );
        pnSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnSanPham.setLayout(null);

        btnSanPham.setBackground(new java.awt.Color(255, 255, 255));
        btnSanPham.setFont(new java.awt.Font("Myriad Pro", 1, 13)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/sanpham.png"))); // NOI18N
        btnSanPham.setText("SẢN PHẦM");
        btnSanPham.setBorder(null);
        btnSanPham.setBorderPainted(false);
        btnGrMenu.add(btnSanPham);
        btnSanPham.setContentAreaFilled(false);
        btnSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });
        pnSanPham.add(btnSanPham);
        btnSanPham.setBounds(40, 0, 140, 60);

        pnW.add(pnSanPham);

        pnLoaiSanPham.setBackground(null
        );
        pnLoaiSanPham.setForeground(null
        );
        pnLoaiSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnLoaiSanPham.setLayout(null);

        btnLoaiSanPham.setBackground(new java.awt.Color(255, 255, 255));
        btnLoaiSanPham.setFont(new java.awt.Font("Myriad Pro", 1, 13)); // NOI18N
        btnLoaiSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/loaisanpham.png"))); // NOI18N
        btnLoaiSanPham.setText("LOẠI SẢN PHẨM");
        btnLoaiSanPham.setBorder(null);
        btnLoaiSanPham.setBorderPainted(false);
        btnGrMenu.add(btnLoaiSanPham);
        btnLoaiSanPham.setContentAreaFilled(false);
        btnLoaiSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLoaiSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLoaiSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSanPhamActionPerformed(evt);
            }
        });
        pnLoaiSanPham.add(btnLoaiSanPham);
        btnLoaiSanPham.setBounds(40, 0, 140, 60);

        pnW.add(pnLoaiSanPham);

        pnHoaDon.setBackground(null
        );
        pnHoaDon.setForeground(null
        );
        pnHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnHoaDon.setLayout(null);

        btnHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setFont(new java.awt.Font("Myriad Pro", 1, 13)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/hoadon.png"))); // NOI18N
        btnHoaDon.setText("HÓA ĐƠN");
        btnHoaDon.setBorder(null);
        btnHoaDon.setBorderPainted(false);
        btnGrMenu.add(btnHoaDon);
        btnHoaDon.setContentAreaFilled(false);
        btnHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        pnHoaDon.add(btnHoaDon);
        btnHoaDon.setBounds(40, 0, 140, 60);

        pnW.add(pnHoaDon);

        pnPhieuNhap.setBackground(null
        );
        pnPhieuNhap.setForeground(null
        );
        pnPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnPhieuNhap.setLayout(null);

        btnPhieuNhap.setBackground(new java.awt.Color(255, 255, 255));
        btnPhieuNhap.setFont(new java.awt.Font("Myriad Pro", 1, 13)); // NOI18N
        btnPhieuNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/phieunhap.png"))); // NOI18N
        btnPhieuNhap.setText("PHIẾU NHẬP");
        btnPhieuNhap.setBorder(null);
        btnPhieuNhap.setBorderPainted(false);
        btnGrMenu.add(btnPhieuNhap);
        btnPhieuNhap.setContentAreaFilled(false);
        btnPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhieuNhap.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuNhapActionPerformed(evt);
            }
        });
        pnPhieuNhap.add(btnPhieuNhap);
        btnPhieuNhap.setBounds(40, 0, 140, 60);

        pnW.add(pnPhieuNhap);

        pnNhanVien.setBackground(null
        );
        pnNhanVien.setForeground(null
        );
        pnNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnNhanVien.setLayout(null);

        btnNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setFont(new java.awt.Font("Myriad Pro", 1, 13)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/nhanvien.png"))); // NOI18N
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setBorder(null);
        btnNhanVien.setBorderPainted(false);
        btnGrMenu.add(btnNhanVien);
        btnNhanVien.setContentAreaFilled(false);
        btnNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        pnNhanVien.add(btnNhanVien);
        btnNhanVien.setBounds(40, 0, 140, 60);

        pnW.add(pnNhanVien);

        pnKhachHang.setBackground(null
        );
        pnKhachHang.setForeground(null
        );
        pnKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnKhachHang.setLayout(null);

        btnKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setFont(new java.awt.Font("Myriad Pro", 1, 13)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/client.png"))); // NOI18N
        btnKhachHang.setText("KHÁCH HÀNG");
        btnKhachHang.setBorder(null);
        btnKhachHang.setBorderPainted(false);
        btnGrMenu.add(btnKhachHang);
        btnKhachHang.setContentAreaFilled(false);
        btnKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        pnKhachHang.add(btnKhachHang);
        btnKhachHang.setBounds(40, 0, 140, 60);

        pnW.add(pnKhachHang);

        pnNhaCungCap.setBackground(null
        );
        pnNhaCungCap.setForeground(null
        );
        pnNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnNhaCungCap.setLayout(null);

        btnNhaCungCap.setBackground(new java.awt.Color(255, 255, 255));
        btnNhaCungCap.setFont(new java.awt.Font("Myriad Pro", 1, 13)); // NOI18N
        btnNhaCungCap.setForeground(new java.awt.Color(255, 255, 255));
        btnNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/nhacungcap.png"))); // NOI18N
        btnNhaCungCap.setText("NHÀ CUNG CẤP");
        btnNhaCungCap.setActionCommand("");
        btnNhaCungCap.setBorder(null);
        btnNhaCungCap.setBorderPainted(false);
        btnGrMenu.add(btnNhaCungCap);
        btnNhaCungCap.setContentAreaFilled(false);
        btnNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhaCungCap.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });
        pnNhaCungCap.add(btnNhaCungCap);
        btnNhaCungCap.setBounds(40, 0, 140, 60);

        pnW.add(pnNhaCungCap);

        getContentPane().add(pnW);
        pnW.setBounds(0, 0, 180, 600);

        pnN.setBackground(new java.awt.Color(91, 209, 215));
        pnN.setAlignmentX(0.0F);
        pnN.setAlignmentY(0.0F);
        pnN.setPreferredSize(new java.awt.Dimension(820, 50));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/exit.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        lbTenBtn.setBackground(null
        );
        lbTenBtn.setFont(new java.awt.Font("Myriad Pro", 1, 20)); // NOI18N
        lbTenBtn.setForeground(new java.awt.Color(255, 255, 255));
        lbTenBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnNLayout = new javax.swing.GroupLayout(pnN);
        pnN.setLayout(pnNLayout);
        pnNLayout.setHorizontalGroup(
            pnNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNLayout.createSequentialGroup()
                .addGap(0, 347, Short.MAX_VALUE)
                .addComponent(lbTenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(btnExit))
        );
        pnNLayout.setVerticalGroup(
            pnNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnNLayout.createSequentialGroup()
                .addComponent(btnExit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnN);
        pnN.setBounds(180, 0, 820, 50);

        pnContent.setBackground(new java.awt.Color(255, 255, 102));
        pnContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnContent.setPreferredSize(new java.awt.Dimension(820, 550));
        pnContent.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(pnContent);
        pnContent.setBounds(180, 50, 820, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        if (JOptionPane.showConfirmDialog(getContentPane(), "Bạn có thực sự muốn thoát?", "Thoát thật hửm?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        tieuDe(btnSanPham);
        pnContent.removeAll();
        pnContent.add(new FrontEndSanPham());
        pnContent.validate();
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new Login().setVisible(true);
        setVisible(false);
        //System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSanPhamActionPerformed
        tieuDe(btnLoaiSanPham);
        pnContent.removeAll();
        pnContent.add(new FrontEndLoaiSanPham());
        pnContent.validate();
    }//GEN-LAST:event_btnLoaiSanPhamActionPerformed

    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
        tieuDe(btnNhaCungCap);
        pnContent.removeAll();
        pnContent.add(new FrontEndNhaCungCap());
        pnContent.validate();
    }//GEN-LAST:event_btnNhaCungCapActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        tieuDe(btnBanHang);
        pnContent.removeAll();
        pnContent.add(new FrontEndBanHang());
        pnContent.validate();
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuNhapActionPerformed
        tieuDe(btnPhieuNhap);
        pnContent.removeAll();
        pnContent.add(new FrontEndPhieuNhap());
        pnContent.validate();
    }//GEN-LAST:event_btnPhieuNhapActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        tieuDe(btnNhapHang);
        pnContent.removeAll();
        pnContent.add(new FrontEndNhapHang());
        pnContent.validate();
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        tieuDe(btnNhanVien);
        pnContent.removeAll();
        pnContent.add(new FrontEndNhanVien());
        pnContent.validate();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        tieuDe(btnKhachHang);
        pnContent.removeAll();
        pnContent.add(new FrontEndKhachHang());
        pnContent.validate();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        tieuDe(btnHoaDon);
        pnContent.removeAll();
        pnContent.add(new FrontEndHoaDon());
        pnContent.validate();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JLabel btnExit;
    private javax.swing.ButtonGroup btnGrMenu;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLoaiSanPham;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNhaCungCap;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnPhieuNhap;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JLabel lbTenBtn;
    private javax.swing.JPanel pnBanHang;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnHoaDon;
    private javax.swing.JPanel pnKhachHang;
    private javax.swing.JPanel pnLoaiSanPham;
    private javax.swing.JPanel pnN;
    private javax.swing.JPanel pnNhaCungCap;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnNhapHang;
    private javax.swing.JPanel pnPhieuNhap;
    private javax.swing.JPanel pnSanPham;
    private javax.swing.JPanel pnW;
    // End of variables declaration//GEN-END:variables
}
