package FrontEnd.LoaiSanPham;

import BackEnd.QuanLyLoaiSanPham.LoaiSanPham;
import BackEnd.QuanLyLoaiSanPham.QuanLyLoaiSanPhamBUS;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class FrontEndLoaiSanPham extends javax.swing.JPanel {

    /**
     * Creates new form FontEndLoaiSanPham
     */
    QuanLyLoaiSanPhamBUS lspCtrl = new QuanLyLoaiSanPhamBUS();

    public FrontEndLoaiSanPham() {
        initComponents();
        getData();
        tbLoaiSanPham.setRowHeight(20);
    }

    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tbLoaiSanPham.getModel();
        // Xóa dữ liệu cũ
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        //Cập nhật dữ liệu mới
        for (LoaiSanPham lsp : lspCtrl.readDB()) {
            model.addRow(lsp.toArray());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grThemSuaXoa = new javax.swing.ButtonGroup();
        sc = new javax.swing.JScrollPane();
        tbLoaiSanPham = new javax.swing.JTable();
        tfMaLSP = new javax.swing.JTextField();
        tfTenLSP = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        tfMoTa = new javax.swing.JTextField();
        pnTimKiem = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        tfTimKiem = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(820, 550));
        setLayout(null);

        tbLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại sản phẩm", "Tên loại sản phẩm", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbLoaiSanPham.getTableHeader().setReorderingAllowed(false);
        tbLoaiSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLoaiSanPhamMouseClicked(evt);
            }
        });
        sc.setViewportView(tbLoaiSanPham);
        tbLoaiSanPham.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbLoaiSanPham.getColumnModel().getColumnCount() > 0) {
            tbLoaiSanPham.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbLoaiSanPham.getColumnModel().getColumn(1).setPreferredWidth(15);
            tbLoaiSanPham.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        add(sc);
        sc.setBounds(135, 70, 550, 300);

        tfMaLSP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Mã loại sản phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        add(tfMaLSP);
        tfMaLSP.setBounds(210, 410, 120, 40);

        tfTenLSP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Tên loại sản phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        add(tfTenLSP);
        tfTenLSP.setBounds(370, 410, 120, 40);

        btnSua.setBackground(new java.awt.Color(0, 77, 97));
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.setBorderPainted(false);
        grThemSuaXoa.add(btnSua);
        btnSua.setPreferredSize(new java.awt.Dimension(90, 30));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua);
        btnSua.setBounds(530, 450, 90, 30);

        btnXoa.setBackground(new java.awt.Color(0, 77, 97));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(null);
        btnXoa.setBorderPainted(false);
        grThemSuaXoa.add(btnXoa);
        btnXoa.setPreferredSize(new java.awt.Dimension(90, 30));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa);
        btnXoa.setBounds(530, 490, 90, 30);

        btnThem.setBackground(new java.awt.Color(0, 77, 97));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.setBorderPainted(false);
        grThemSuaXoa.add(btnThem);
        btnThem.setPreferredSize(new java.awt.Dimension(90, 30));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem);
        btnThem.setBounds(530, 410, 90, 30);

        tfMoTa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Mô tả loại sản phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        add(tfMoTa);
        tfMoTa.setBounds(210, 470, 280, 40);

        pnTimKiem.setBackground(null
        );
        pnTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Nhập vào loại sản phẩm", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        pnTimKiem.setPreferredSize(new java.awt.Dimension(180, 50));

        btnTimKiem.setBackground(null);
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/timkiem.png"))); // NOI18N
        btnTimKiem.setText(null);
        btnTimKiem.setBorder(null);
        btnTimKiem.setBorderPainted(false);
        btnTimKiem.setContentAreaFilled(false);
        btnTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTimKiemKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnTimKiemLayout = new javax.swing.GroupLayout(pnTimKiem);
        pnTimKiem.setLayout(pnTimKiemLayout);
        pnTimKiemLayout.setHorizontalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemLayout.createSequentialGroup()
                .addComponent(tfTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnTimKiemLayout.setVerticalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfTimKiem, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnTimKiem);
        pnTimKiem.setBounds(505, 10, 180, 45);
    }// </editor-fold>//GEN-END:initComponents

    private void tbLoaiSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLoaiSanPhamMouseClicked
        DefaultTableModel model = (DefaultTableModel) tbLoaiSanPham.getModel();
        tfMaLSP.setText(model.getValueAt(tbLoaiSanPham.getSelectedRow(), 0).toString());
        tfTenLSP.setText(model.getValueAt(tbLoaiSanPham.getSelectedRow(), 1).toString());
        tfMoTa.setText(model.getValueAt(tbLoaiSanPham.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tbLoaiSanPhamMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        JTextField[] tfTT = {tfMaLSP, tfTenLSP, tfMoTa};
        for (JTextField tf : tfTT) {
            if (tf.getText().matches("") || tf.getText().matches("\\s+")) {
                JOptionPane.showMessageDialog(this, "Điền không đủ thông tin!");
                return;
            }
        }
        if (lspCtrl.add( tfMaLSP.getText(), tfTenLSP.getText(), tfMoTa.getText())) {
            getData();
            JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thất bại!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (tbLoaiSanPham.getSelectedRow() != -1) {
            if (lspCtrl.update(tfMaLSP.getText(), tfTenLSP.getText(), tfMoTa.getText())) {
                getData();
                JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thành công!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn loại sản phẩm cần sửa");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (tbLoaiSanPham.getSelectedRow() != -1) {
            if (lspCtrl.delete(tfMaLSP.getText())) {
                getData();
                JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thành công!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn loại sản phẩm cần sửa");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbLoaiSanPham.getModel();

        ArrayList<LoaiSanPham> dssp = lspCtrl.search(tfTimKiem.getText().trim());
        if (dssp.size() > 0) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            for (LoaiSanPham sp : dssp) {
                model.addRow(sp.toArray());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy loai sản phẩm " + tfTimKiem.getText().trim());
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tfTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTimKiemKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) tbLoaiSanPham.getModel();

            ArrayList<LoaiSanPham> dssp = lspCtrl.search(tfTimKiem.getText().trim());
            if (dssp.size() > 0) {
                while (model.getRowCount() > 0) {
                    model.removeRow(0);
                }
                for (LoaiSanPham sp : dssp) {
                    model.addRow(sp.toArray());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy loai sản phẩm " + tfTimKiem.getText().trim());
            }

        }
    }//GEN-LAST:event_tfTimKiemKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup grThemSuaXoa;
    private javax.swing.JPanel pnTimKiem;
    private javax.swing.JScrollPane sc;
    private javax.swing.JTable tbLoaiSanPham;
    private javax.swing.JTextField tfMaLSP;
    private javax.swing.JTextField tfMoTa;
    private javax.swing.JTextField tfTenLSP;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables
}
